import Head from "next/head";
import { useRouter } from "next/navigation";

export async function getStaticProps() {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const data = await res.json();

  return {
    props: {
      posts: data.slice(0, 15),
    },
  };
}

const PostList = ({ posts }) => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Pwa next app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      {posts.map((post) => {
        return (
          <div
            key={post.id}
            className="ssg-styles"
            onClick={() => router.push(`/posts/${post.id}`)}
          >
            <h3>{post.id}</h3>
            <h2>{post.title}</h2>
          </div>
        );
      })}
    </>
  );
};
export default PostList;
