import Head from "next/head";

function Home() {
  return (
    <div className="container">
      <Head>
        <title>Pwa next app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <section>
        <div className="heroSection">
          <h1>👋 Hey </h1>
          <h3>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim,
            voluptates.
          </h3>
          <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sit
            voluptates qui incidunt laudantium, itaque iste veritatis. Alias
            dolores cupiditate, voluptas neque nisi quasi ratione libero maxime
            ducimus aliquid nulla nostrum dolorem dolorum laudantium unde dicta.
            Eius dolorum accusantium natus est repudiandae! Eius totam provident
            quibusdam laudantium, voluptatem vero sed impedit deleniti error
            iusto incidunt maiores expedita autem, consectetur quod quae, illum
            molestias? Quia saepe ex, sapiente excepturi et quasi veritatis
            dignissimos sint, laudantium sit perspiciatis mollitia, similique
            vero ipsa officiis inventore dolore quaerat praesentium beatae
            ratione exercitationem possimus pariatur! Delectus dignissimos
            voluptatibus illum cum vitae nulla hic ratione dicta!
          </p>
        </div>
      </section>
    </div>
  );
}

export default Home;
